name = "Artists"
license = "Unlicense License"
licenselink = "//github.com/digitalcraftsman/hugo-artists-theme/blob/master/LICENSE"
description = "A one page portfolio for freelancers, programmers and designers."
homepage = "//github.com/digitalcraftsman/hugo-artists-theme"
tags = ["portfolio", "showcase", "skills", "clients", "contact form"]
features = ["about section with skill rating", "stylish portfolio with slider", "carousel for client's quotes", "contact form"]
min_version = 0.20

[author]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman"

# If porting an existing theme
[original]
  name = "Travis Neilson"
  homepage = "//travisneilson.com/"
  repo = "//github.com/DevTips/Artists-Theme"
